CREATE TABLE people(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) NOT NULL,
    patronymic varchar(50) NOT NULL,
    surname varchar(50) NOT NULL,
    birthday date NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
);

CREATE TABLE books(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    date date NOT NULL,
    people_id int DEFAULT NULL REFERENCES people(id) ON DELETE Set null ON UPDATE Cascade
);